In [8]:
import numpy as np
import cv2
img=np.ones((6,6,3), dtype=np.uint8)
img[:,:,0]=32
img[:,:,1]=32
img[:,:,2]=32
cv2.imwrite('test.jpg',img)

True

In [3]:
import numpy as np
import cv2
from PIL import Image
# a nice example
image_id = 'Ciktw3i-ar5zee06SKJElQ'
instance_path = "/mnt/instance/{}.png".format(image_id)
instance_img = cv2.imread(instance_path,0)
height, width = instance_img.shape[0:2]
print(height, width)

print(instance_img[1559,1861])
print(instance_img[1270,3255])
instance_ary = np.array(instance_img, dtype=np.uint16)
print(instance_ary)

2448 3264
55
55
[[30 30 30 ... 17 17 17]
 [30 30 30 ... 17 17 17]
 [30 30 30 ... 17 17 17]
 ...
 [15 15 15 ... 13 13 13]
 [15 15 15 ... 13 13 13]
 [15 15 15 ... 13 13 13]]


In [28]:
instance_image = Image.open(instance_path)
instance_array = np.array(instance_image, dtype=np.uint16)
print(instance_array)
print(instance_array[1559,1861])
print(instance_array[1270,3255])
instance_ids = np.unique(instance_array)
print(instance_ids)
mask=instance_array[:,:]==512

instance_img[:,:]=0
instance_img[mask]= 250
ret, binaryimg=cv2.threshold(instance_img,127, 255, cv2.THRESH_BINARY)
x,y,w,h=cv2.boundingRect(instance_img)
print(x, y, w, h)
origin_img_path='/mnt/image/Ciktw3i-ar5zee06SKJElQ.jpg'
origin_img=cv2.imread(original_img_path)
import numpy as np
import os
from PIL import Image

working_dir='/mnt/instance/'
# instance文件夹下是16位的灰度图，可以容纳最多256类，而且每类可以有256个instance_id
txt_root='/home/arc-cxj9600/transform-cityspace/bboxtxt'
for root, dirs, files in os.walk(working_dir):
    for i, file in enumerate(files):
        #if i==1:
        #    break
        file_path=os.path.join(working_dir, file)
        instance_image = Image.open(file_path)
        auxiliary_image = cv2.imread(file_path,0)
        instance_array = np.array(instance_image, dtype=np.uint16)
        
        #获取每个像素点的类别标签和instance_id标签
        instance_label_array = np.array(instance_array / 256, dtype=np.uint8)
        instance_id_array = np.array(instance_array % 255, dtype=np.uint8)
        
        instance_ids = np.unique(instance_array)
        
        instance_list=[]
        for instance_value in instance_ids:
            mask=instance_array[:,:]==instance_value
            label=int(instance_value / 256)
            
            # 获得某个instance的二值图
            auxiliary_image[:,:]=0
            auxiliary_image[mask]=255
            
            # 得到某个instance的外接矩形参数， [x,y]是左上点坐标， [x+w, y+h]是右下点坐标
            x, y, w, h=cv2.boundingRect(auxiliary_image)
            instance_list.append([label,x, y, x+w, y+h])
            
        final_instance_list=[]
        # Python中没有switch语句，可以使用dict来实现这一功能
        label_mapping_dict={27:1, 13:2, 15:2, 17:3, 19:4, 20:4, 21:4, 22:4, 1:4, 30:5, 54:6, 56:6, 52:6, 57:6, 59:6, 60:6, 61:6, 62:6, 24:7}
        for idx, bbox in enumerate(instance_list):
            if bbox[0] in label_mapping_dict.keys():
                bbox[0]=label_mapping_dict[bbox[0]]
                final_instance_list.append(bbox)
        
        txtfile_name=os.path.join(txt_root,'{}.txt'.format(file[:-4]))
        with open(txtfile_name, 'w') as f:
            print(str(bbox)[1:-2].replace(',',' '))
            for bbox in final_instance_list:
                f.write(str(bbox)[1:-2].replace(',', ' '))
                f.write('\n')
            n_img_path)
cv2.rectangle(origin_img, (x,y), (x+w, y+h), (0,255,0),2)
cv2.imwrite('instance_example.png',origin_img)

[[7680 7680 7680 ... 4352 4352 4352]
 [7680 7680 7680 ... 4352 4352 4352]
 [7680 7680 7680 ... 4352 4352 4352]
 ...
 [3840 3840 3840 ... 3328 3328 3328]
 [3840 3840 3840 ... 3328 3328 3328]
 [3840 3840 3840 ... 3328 3328 3328]]
14085
14086
[  512  1536  2048  3328  3840  4352  4864  4865  4866  4867  4868  6144
  6912  7680  8192  8193 11264 11520 11521 11522 11523 11524 11525 11526
 11527 11528 11529 11530 11531 11532 11533 11534 11535 12288 12289 12290
 12291 12292 12293 12294 12295 12296 12800 12801 12802 12803 14080 14081
 14082 14083 14084 14085 14086 16640]
629 1612 788 836


True

In [13]:
instance_label_array = np.array(instance_array / 256, dtype=np.uint8)
instance_ids_array = np.array(instance_array % 256, dtype=np.uint8)
print(instance_ids_array)
print(instance_ids_array[1559,1861])
print(instance_ids_array[1270,3255])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
5
6


In [ ]:
import numpy as np
import os
from PIL import Image

working_dir='/mnt/instance/'
txt_root='/home/arc-cxj9600/transform-cityspace/bboxtxt'
for root, dirs, files in os.walk(working_dir):
    for i, file in enumerate(files):
        #if i==1:
        #    break
        file_path=os.path.join(working_dir, file)
        instance_image = Image.open(file_path)
        auxiliary_image = cv2.imread(file_path,0)
        instance_array = np.array(instance_image, dtype=np.uint16)
        
        instance_label_array = np.array(instance_array / 256, dtype=np.uint8)
        instance_id_array = np.array(instance_array % 255, dtype=np.uint8)
        
        instance_ids = np.unique(instance_array)
        
        instance_list=[]
        for instance_value in instance_ids:
            mask=instance_array[:,:]==instance_value
            label=int(instance_value / 256)
            
            # 获得某个instance的二值图
            auxiliary_image[:,:]=0
            auxiliary_image[mask]=255
            
            # 得到某个instance的外接矩形参数， [x,y]是左上点坐标， [x+w, y+h]是右下点坐标
            x, y, w, h=cv2.boundingRect(auxiliary_image)
            #print(x,y,w,h)
            instance_list.append([label,x, y, x+w, y+h])
            
        final_instance_list=[]
        label_mapping_dict={27:1, 13:2, 15:2, 17:3, 19:4, 20:4, 21:4, 22:4, 1:4, 30:5, 54:6, 55:6, 56:6, 52:6, 57:6, 59:6, 60:6, 61:6, 62:6, 24:7}
        for idx, bbox in enumerate(instance_list):
            if bbox[0] in label_mapping_dict.keys():
                bbox[0]=label_mapping_dict[bbox[0]]
                final_instance_list.append(bbox)
        
        txtfile_name=os.path.join(txt_root,'{}.txt'.format(file[:-4]))
        with open(txtfile_name, 'w') as f:
            for bbox in final_instance_list:
                f.write(str(bbox)[1:-1].replace(',', ' '))
                f.write('\n')
            
                

In [11]:
# This cell and the cell below are used to test if the bbox coordinates (x,y) and (x+w,y+h) are correct 
import numpy as np
import cv2
from PIL import Image
# a nice example
image_id = 'bjLOBklnyEIKyfeVvR4pmA'
instance_path = "/mnt/instance/{}.png".format(image_id)
instance_img = cv2.imread(instance_path,0)
height, width = instance_img.shape[0:2]
print(height, width)
instance_image = Image.open(instance_path)
instance_ary = np.array(instance_img, dtype=np.uint16)
instance_array = np.array(instance_image, dtype=np.uint16)
print(instance_array)

instance_ids = np.unique(instance_array)
print(instance_ids)
instance_label = instance_ids // 256
instance_id = instance_ids % 256
print(instance_label)
print(instance_id)

2448 3264
[[6912 6912 6912 ... 6912 6912 6912]
 [6912 6912 6912 ... 6912 6912 6912]
 [6912 6912 6912 ... 6912 6912 6912]
 ...
 [3328 3328 3328 ... 3328 3328 3328]
 [3328 3328 3328 ... 3328 3328 3328]
 [3328 3328 3328 ... 3328 3328 3328]]
[    0   512  1536  3328  3840  4352  6144  6912  7424  7680 11264 11265
 11266 11267 11268 11269 11270 11271 11272 11273 11274 11275 11520 11521
 11522 11523 11524 11525 11526 11527 11528 11529 11530 11531 11532 11533
 11534 11535 11536 11537 11538 11539 11540 11541 11542 11543 11544 11545
 11546 11547 11548 11549 11550 11551 11552 11553 11554 11555 11556 11557
 11558 11559 11560 12800 12801 12802 12803 14080 14081 14082 14083 14084
 14085 16128 16640]
[ 0  2  6 13 15 17 24 27 29 30 44 44 44 44 44 44 44 44 44 44 44 44 45 45
 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45
 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 50 50 50 50 55 55 55 55 55
 55 63 65]
[ 0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10 11  0  1
 

In [12]:
mask=instance_array[:,:]==14085
instance_img[:,:]=0
instance_img[mask]=255
x, y, w, h=cv2.boundingRect(instance_img)
print(x,y,w,h)
orgimg_path = "/mnt/image/{}.jpg".format(image_id)
orgimg=cv2.imread(orgimg_path)
cv2.rectangle(orgimg,(x,y),(x+w, y+h),(0,0,255),2)
cv2.imwrite('instance_example.png',orgimg)

1351 1495 149 127


True

In [13]:
bbox_path="/mnt/bboxtxt/{}.txt".format(image_id)
for line in open(bbox_path, "r"):
    print(line)

2  0  1489  3264  244

2  1741  1556  3264  181

3  2290  975  3264  164

7  77  1544  2895  244

1  0  0  3264  136

5  0  656  3101  161



In [34]:
import os
import sys
import cv2
import numpy as np

basedir = "/mnt"
bboxdir = os.path.join(basedir, "bboxtxt")
maskdir = os.path.join(basedir, "annotation_gray256256")
imagedir = os.path.join(basedir, "image")

bboxtxt_name="__mcuCxPdWr9uat9bFikyg"
bbox_path =  os.path.join(bboxdir, bboxtxt_name+'.txt')
img_path =  os.path.join(imagedir, bboxtxt_name+'.jpg')

_COLOR_ = ((255,0,0), (0,255,0), (0,0,255), (255,255,0), (255,0,255),(0,255,255), (255,128,0), (128,0,255))

img = cv2.imread(img_path)
# 读取.txt文件中的每一行
# for line in open(bbox_path, 'r')
for line in open(bbox_path, 'r'):
    print(line)
    ind, xmin, ymin, xmax, ymax = line.split("  ")
    ind, xmin, ymin, xmax, ymax = int(ind), int(xmin), int(ymin), int(xmax), int(ymax)
    
    if ind in [4, 6]:
        img = cv2.rectangle(img, (xmin, ymin), (xmax, ymax), _COLOR_[ind], 3)
        
cv2.imwrite('instance_example.jpg', img)

2  0  1699  3264  2335

3  0  498  3264  1710

4  654  1451  727  1599

4  1423  1601  1452  1650

4  1485  1634  1512  1664

4  1584  1687  1603  1706

4  1172  1547  1220  1620

7  0  1699  3264  2284

1  0  0  3264  1661

6  1171  1593  1218  1619

6  1723  1702  1775  1714

6  1831  1696  1891  1719

6  2030  1656  2105  1729

6  1878  1612  2034  1737



True