In [1]:
# Python面向对象Tutorial
# __str__和__repr__两个magic methods,控制对象如何转换成string输出

In [2]:
# Python 类定义中常用到的super()函数
# super()是python中实现继承的重要一环
# super() gives you access to methods in a superclass from the subclass that inherits from it.

In [1]:
import tensorflow as tf

In [2]:
#在Tensorflow中，一般使用 tf.train.Saver()定义的存储器对象来保存模型，会得到如下文件列表：
#checkpoint
#model.ckpt.data-00000-of-00001
#model.ckpt.index
#model.ckpt.meta

#参考博客https://www.jarvis73.cn/2018/04/25/Tensorflow-Model-Save-Read/

In [12]:
# .data文件可以查询到参数名和参数值，使用下面的命令可以查询保存在文件中的全部变量{名：值}对
from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
# Tensorflow中print_tensors_in_checkpoint_file这个函数可以把所有参数的名称和值打印出来
print_tensors_in_checkpoint_file('/home/arc-cxj9600/hdrnet/pretrained/upgraded_from_sig2017.ckpt-0', None, True)
# 在pretrained文件夹下面有以下几个文件：
# checkpoint
# upgraded_from_sig2017.ckpt-0.data-00000-of-00001
# upgraded_from_sig2017.ckpt-0.index
# upgraded_from_sig2017.ckpt-0.meta

tensor_name:  global_step
0
tensor_name:  inference/coefficients/global/conv1/biases
[-7.48705491e-02 -7.11692646e-02  6.57041147e-02 -6.78079277e-02
 -1.61040381e-01  1.57753862e-02  1.08621083e-01 -1.16596657e-05
 -1.37174383e-01  1.90012027e-02 -2.15974171e-02  1.28517166e-01
  5.15935868e-02 -1.28864229e-01 -1.73299462e-01  3.12318802e-02
 -9.68881398e-02  1.00718461e-01  5.89958616e-02  3.13788764e-02
  1.07288599e-01  4.55850437e-02  3.68461125e-02  5.63385226e-02
  8.96210223e-02  1.41002700e-01 -1.06244935e-02 -7.25887418e-02
  1.07994199e-01  1.08807661e-01  9.12803262e-02 -2.16664523e-02
  2.70137265e-02 -4.68982346e-02 -2.08554476e-01 -9.31006521e-02
  5.64857461e-02  3.84434797e-02  1.23683989e-01  2.67724451e-02
 -3.58554609e-02 -5.79316467e-02  4.05648723e-02 -1.77288547e-01
  3.67102623e-02 -1.72879510e-02 -2.72457510e-01  3.49230394e-02
 -4.10896838e-01 -5.31671606e-02  6.65090755e-02  2.68727578e-02
  9.28508416e-02  9.13995132e-02  5.80277145e-02 -3.37618321e-01
 -3.9

In [13]:
ckpt=tf.train.get_checkpoint_state('/home/arc-cxj9600/hdrnet/pretrained/')
print(ckpt.model_checkpoint_path)

/home/arc-cxj9600/hdrnet/pretrained/upgraded_from_sig2017.ckpt-0


In [14]:
#https://blog.csdn.net/leviopku/article/details/78510977
# Tensorflow中可以用tf.train.NewCheckpointReader这个函数来根据某个tensor名获取tensor变量
reader=tf.train.NewCheckpointReader(ckpt.model_checkpoint_path)
all_variabels = reader.get_variable_to_shape_map()
w1=reader.get_tensor("inference/coefficients/splat/conv1/weights")
w2=reader.get_tensor("inference/coefficients/splat/conv2/weights")
w3=reader.get_tensor("inference/coefficients/splat/conv3/weights")
w4=reader.get_tensor("inference/coefficients/splat/conv4/weights")

b1=reader.get_tensor("inference/coefficients/splat/conv1/biases")
b2=reader.get_tensor("inference/coefficients/splat/conv2/biases")
b3=reader.get_tensor("inference/coefficients/splat/conv3/biases")
b4=reader.get_tensor("inference/coefficients/splat/conv4/biases")

print(w1.shape)
print(b1.shape)
print(w2.shape)
print(b2.shape)
print(w3.shape)
print(b3.shape)
print(w4.shape)
print(b4.shape)


(3, 3, 3, 8)
(8,)
(3, 3, 8, 16)
(16,)
(3, 3, 16, 32)
(32,)
(3, 3, 32, 64)
(64,)


In [21]:
import pickle
pretrained_dict={'conv1': w1,
                 'conv2': w2,
                 'conv3': w3}

print(type(pretrained_dict))
print(pretrained_dict)
output_file=open('pretrained_dict.pkl', 'wb')

pickle.dump(pretrained_dict, output_file)

output_file.close

<class 'dict'>
{'conv3': array([[[[ 0.05267376, -0.02157901, -0.20675917, ..., -0.21658617,
          -0.22743711, -0.21584247],
         [ 0.04784281, -0.05606179, -0.09151246, ...,  0.09848857,
          -0.13070007, -0.11717089],
         [ 0.17586978,  0.07798652, -0.02228956, ..., -0.17286454,
          -0.21751903,  0.10004684],
         ...,
         [ 0.09722579, -0.25081012,  0.0378521 , ...,  0.11612524,
           0.00961839, -0.4456286 ],
         [ 0.12598543,  0.00638138, -0.01492087, ...,  0.00241045,
           0.0237198 ,  0.04671315],
         [ 0.13208237, -0.27478704, -0.07130063, ...,  0.15153913,
           0.00331876, -0.11167039]],

        [[ 0.17473364, -0.03247093, -0.18217035, ..., -0.26255983,
          -0.05053028, -0.30721048],
         [-0.05167476, -0.01957873, -0.17679417, ..., -0.09707183,
          -0.05066244, -0.22472063],
         [-0.04259989, -0.02780315, -0.23802388, ..., -0.05178493,
           0.03077035,  0.04078705],
         ...,
         

<function BufferedWriter.close>

In [17]:
import pprint
pkl_file = open('pretrained_dict.pkl', 'rb')
pretrained_dict=pickle.load(pkl_file)
pprint.pprint(pretrained_dict)
print(type(pretrained_dict))
pkl_file.close()

EOFError: Ran out of input

In [35]:
import numpy as np
import tensorflow as tf

ar1=np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.float32)
t1=tf.convert_to_tensor(ar1)
print(t1)

# tf.square 就是对 tensor做element-wise的平方
square=tf.square(t1, name='square')

lognei = tf.reduce_mean(square, axis=[1])

with tf.Session() as sess:
    print(sess.run(t1))
    print(sess.run(square))
    print(sess.run(lognei))

Tensor("Const_13:0", shape=(3, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]
[ 4.6666665 25.666666  64.666664 ]
